---
# See https://github.com/puppetlabs/puppetlabs_spec_helper for reference
fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '6.2.0'
    firewalld:
      repo: 'puppet/firewalld'
      ref: '4.2.4'
    acl:
      repo: 'puppetlabs/acl'
      ref: '3.1.0'
    augeas_core:
      repo: 'puppetlabs/augeas_core'
      ref: '1.0.5'
