---
# See https://github.com/puppetlabs/puppetlabs_spec_helper for reference
fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '6.2.0'
    firewalld:
      repo: 'puppet/firewalld'
      ref: '4.2.4'
